version: "3"
services:
  home-use-database:
    image: mongo:3.2.4
    container_name: "home-use-database"
    ports:
      - 27017:27017
    command: --smallfiles
  api:
    build: .
    ports:
      - 8080:8080
    links:
      - home-use-database
    env_file:
      - .env
    environment:
      MONGO_URI: 'mongodb://home-use-database:27017/home-use-local'
