FROM adoptopenjdk:11-jdk
EXPOSE 8080
ADD build/libs/home-use.jar /app/
WORKDIR /app
CMD java -agentlib:jdwp=transport=dt_socket,server=n,address=localhost:7005,suspend=y,onuncaught=n -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=docker -cp . -jar home-use.jar
