server:
    port: 8080
spring:
    data:
        mongodb:
            uri: ${MONGO_URI}
    jpa:
        properties:
            hibernate:
                show_sql: true
    security:
        #    https://docs.spring.io/spring-security/site/docs/5.2.x/reference/html/oauth2.html#oauth2login-boot-property-mappings
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_SECRET}
